name: MyItem
main: myitem\Main
author: pmmdst
editor: KhanggTrann
api: 3.0.0
version: 0.0.1
#Xin hãy tôn trọng tác giả !!! Plugin hoàn toàn miễn phí và sẽ cập nhật đều đặn !!!

commands:
 mi:
  description: My Item
  permission: myitem.command
  default: op
